Warning: tst_test2.cpp: (8, 4): Unnamed temporary of type 'bcemt_LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (9, 4): Unnamed temporary of type 'bcemt::LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (14, 4): Unnamed temporary of type 'bcemt_LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (15, 4): Unnamed temporary of type 'bcemt::LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (24, 8): Unnamed temporary of type 'bcemt_LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (25, 8): Unnamed temporary of type 'bcemt::LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (30, 8): Unnamed temporary of type 'bcemt_LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (31, 8): Unnamed temporary of type 'bcemt::LockGuard' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (39, 8): Unnamed temporary of type 'bdema_ManagedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (40, 8): Unnamed temporary of type 'bdema::ManagedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (45, 8): Unnamed temporary of type 'bdema_ManagedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (46, 8): Unnamed temporary of type 'bdema::ManagedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (51, 8): Unnamed temporary of type 'bcema_SharedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (52, 8): Unnamed temporary of type 'bcema::SharedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (57, 8): Unnamed temporary of type 'bcema_SharedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
Warning: tst_test2.cpp: (58, 8): Unnamed temporary of type 'bcema::SharedPtr' created -- will not guard anything, needs a name -- i.e. 'ptr', 'guard', 'proctor', or 'deleter'.
