.. |br| raw:: html

   <br/>

.. role:: black
.. role:: gray
.. role:: grey
.. role:: silver
.. role:: white
.. role:: maroon
.. role:: red
.. role:: magenta
.. role:: fuchsia
.. role:: pink
.. role:: orange
.. role:: yellow
.. role:: lime
.. role:: green
.. role:: olive
.. role:: teal
.. role:: cyan
.. role:: aqua
.. role:: blue
.. role:: navy
.. role:: purple

.. role:: underline
.. role:: overline
.. role:: blink
.. role:: strike
