[% PROCESS svc_util.t -%]
MKINCL?=/bbsrc/mkincludes/
include \$(MKINCL)machdep.newlink
include /bbsrc/tools/data/libmacros.mk

USER_FFLAGS=\$(FPIC)

USER_CFLAGS=\$(WALL) \$(CPIC) -I.

[% MSGPKG %]_CPPFLAGS ?= -I.

USER_CPPFLAGS  = -I.
USER_CPPFLAGS += \$([% MSGPKG %]_CPPFLAGS)

IS_BDE=yes
IS_PTHREAD=yes
IS_EXCEPTION=yes

# Comment the line below to disable dependency builds
IS_DEPENDS_NATIVE=yes

# Remove "yes" in the macro definition below to disable inlining
INLINING=yes

ANAME=libs_[% service %].a
SNAME=libs_[% service %].so

###
### DO NOT CHANGE THE DEFINITION OF THE 'MSGOBJS' MACRO
###
MSGOBJS=\
[% IF pkg == msgpkg -%]
[% FOREACH componentName = componentNames -%]
[% msgpkg %]_[% componentName %].o \
[% END -%]
[% END -%]

###
### Add additional components to the 'AOBJS' macro
###
AOBJS=\
\$(MSGOBJS) \
[% pkg %]_buildopts.o \
[% pkg %]_manifest.o \
[% pkg %]_entry.o \
[% pkg %]_requestcontext.o \
[% pkg %]_requestrouter.o \
[% pkg %]_requestprocessor.o \
[% pkg %]_version.o \
[% pkg %]_versiontag.o \

SOBJS=\$(AOBJS)

-include local.mk

include \$(MKINCL)/\$(if \$(BAS_LINK_STATIC),linklib,linkso).newlink

# \$Id\$ \$CSID\$ \$CCId\$
# GENERATED BY [% version %] [% timestamp %]
