[% PROCESS component_util.t -%]
// [% String.new(basename).append('.cpp').lower %]   -*-C++-*-   [% -%]
[%- %]GENERATED FILE -- DO NOT EDIT

#include <bdes_ident.h>
BDES_IDENT_RCSID([% basename %]_cpp,"\$Id\$ \$CSID\$ \$CCId\$")

#include <[% String.new(basename).append('.h').lower %]>

[% IF cmp.supportsAggregateConversion -%]
[% IF cmp.hasCustomizedType -%]
#include <bdede_utf8util.h>
[% ELSE -%]
#include <bcem_aggregate.h>
[% END -%]
#include <bcem_aggregateutil.h>

[% END -%]
[% IF cmp.supportsIntrospection -%]
#include <bdeat_formattingmode.h>
[% END -%]
#include <bdeat_valuetypefunctions.h>
[% IF opts.ignoreCase -%]
#include <bdeu_chartype.h>
[% END -%]
#include <bdeu_print.h>
#include <bdeu_printmethods.h>
#include <bdeu_string.h>

[% FOREACH cmp.include -%]
#include <[% file %]>
[% END -%]

#include <bsls_assert.h>

#include <ostream>
#include <iomanip>

namespace BloombergLP {
namespace [% namespace %] {
[%- FOREACH class = cmp.classes -%]
[%- IF "sequence" == class.trait -%]
[%- SET sequence = class -%]
[%- PROCESS sequence_cpp.t -%]
[%- INCLUDE sequenceMethodDefinitions -%]
[%- ELSIF "choice" == class.trait -%]
[%- SET choice = class -%]
[%- PROCESS choice_cpp.t -%]
[%- INCLUDE choiceMethodDefinitions -%]
[%- ELSIF "customizedtype" == class.trait -%]
[%- SET customizedtype = class -%]
[%- PROCESS customizedtype_cpp.t -%]
[%- INCLUDE customizedtypeMethodDefinitions -%]
[%- ELSIF "enumeration" == class.trait -%]
[%- SET enumeration = class -%]
[%- PROCESS enumeration_cpp.t -%]
[%- INCLUDE enumerationMethodDefinitions -%]
[%- END -%]
[%- END -%]

}  // close namespace [% namespace %]
}  // close namespace BloombergLP

// GENERATED BY [% version %] [% timestamp %]
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., [% year.format %]
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------ END-OF-FILE ---------------------------------
