[% PROCESS configschema_util.t -%]
// [% pkg %]_configschema.cpp   -*-C++-*-   [% -%]
[%- %]GENERATED FILE -- DO NOT EDIT

#include <bdes_ident.h>
BDES_IDENT_RCSID([% pkg %]_configschema_cpp,"\$Id\$ \$CSID\$ \$CCId\$")

#include <[% pkg %]_configschema.h>

namespace BloombergLP {
namespace [% namespace %] {

// CONSTANTS

const char ConfigSchema::TEXT[] =
[% schema.text | c_str %];

}  // close namespace [% namespace %]
}  // close namespace BloombergLP

// GENERATED BY [% version %] [% timestamp %]
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., [% year.format %]
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------ END-OF-FILE ---------------------------------
