[% PROCESS svc_util.t -%]
#!/bin/ksh
# \$Id\$ \$CSID\$ \$CCId\$

task=[% service %]
taskdir=\$1
logfile=\$2

exec \$taskdir/\$task.tsk -l \$logfile \$taskdir/\$task.cfg

# GENERATED BY [% version %] [% timestamp %]
