[% PROCESS svc_util.t -%]
#!/bin/ksh
# \$Id\$ \$CSID\$ \$CCId\$

[% SERVICE %]_BIN=`dirname $0`
[[ -n \${[% SERVICE %]_BIN##/*} ]] && [% -%]
                        [%- %][% SERVICE %]_BIN=\$PWD/\${[% SERVICE %]_BIN#.}

task=[% service %]

[% SERVICE %]_LOGDN=/bb/data
[% SERVICE %]_LOGBN=\$task.log
[% SERVICE %]_LOGFILE=\$[% SERVICE %]_LOGDN/\$[% SERVICE %]_LOGBN

openpipe \$task
echo "starting task \$task" >> /tmp/\$task.fifo

# Remove log files older than 4 days
[% SET offlen = SERVICE.length -%]
[% SET offset = String.new(' ').repeat(offlen) -%]
echo "start \$task /bb/bin/baellog_cleanup.pl -d \$[% SERVICE %]_LOGDN \
                                             -e \$[% SERVICE %]_LOGBN \
                                             -q 4 [% offset %]      \
          >> /tmp/\$task.fifo 2>&1"               [% offset %]       \
    >> /tmp/p.fifo

# Start the service
echo "pstart \$task \$[% SERVICE %]_BIN/pstart_[% service %] [% -%]
                                             [%- %]\$[% SERVICE %]_BIN [% -%]
                                             [%- %]\$[% SERVICE %]_LOGFILE \
          >> /tmp/\$task.fifo 2>&1"                              [% -%]
                                                   [%- %][% offset %]      \
    >> /tmp/p.fifo

#==================================
# IMPORTANT WARNING: READ CAREFULLY
#==================================
# The following 'send' registers the task with {PWHO SYSCHK<GO>}.  Syschk
# prints errors in act.log if a registered task is not up.  However, since
# syschk is executed at the end of the rstrt script, this particular send
# command will have no effect if run from rstrt.  In this case, you must add
# your task name to /bb/data/syschk.cmd.

send syschk addt \$task

# GENERATED BY [% version %] [% timestamp %]
