[% PROCESS svc_util.t -%]
#!/bin/ksh
# \$Id\$ \$CSID\$ \$CCId\$

task=[% service %]

openpipe \$task
echo "stopping task $task" >> /tmp/\$task.fifo

send syschk delt \$task
/bb/bin/mktemp \$task
send \$task exit

# GENERATED BY [% version %] [% timestamp %]
