[% PROCESS svc_util.t -%]
// [% pkg %]_version.cpp   -*-C++-*-

#include <bdes_ident.h>
BDES_IDENT_RCSID([% pkg %]_version_cpp,"\$Id\$ \$CSID\$ \$CCId\$")

#include <[% pkg %]_version.h>
[% IF 'svc' == opts.currentMode -%]
#include <[% pkg %]_versiontag.h>
[% END -%]

namespace BloombergLP {
namespace [% namespace %] {

                               // --------------
                               // struct Version
                               // --------------

[% IF 'svc' == opts.currentMode -%]
// Increment the version in the following way:
// - increment VERSION_PATCH for each binary compatible bug fix
// - increment VERSION_MINOR for each binary compatible interface extension
// - increment VERSION_MAJOR for each source incompatible change

#define STRINGIFY2(a) #a
#define STRINGIFY(a)  STRINGIFY2(a)

#define [% PKG %]_VERSION_PATCH  0
#define [% PKG %]_VERSION_STRING "BLP_BAS_LIB_[% PKG %]_" \
        STRINGIFY([% PKG %]_VERSION_MAJOR) \
    "." STRINGIFY([% PKG %]_VERSION_MINOR) \
    "." STRINGIFY([% PKG %]_VERSION_PATCH)
[% ELSE -%]
#define [% PKG %]_VERSION_STRING "BLP_BAS_APP_[% PKG %]_1.0.0"
[% END -%]

const char *Version::d_ident = "\$Id: "[% PKG %]_VERSION_STRING" \$";
const char *Version::d_what  = "@(#)"[% PKG %]_VERSION_STRING;

const char *Version::d_version           = [% PKG %]_VERSION_STRING;
const char *Version::d_dependencies      = "";
const char *Version::d_buildInfo         = "";
const char *Version::d_timestamp         = "";
const char *Version::d_sourceControlInfo = "";

}  // close namespace [% namespace %]
}  // close namespace BloombergLP

// GENERATED BY [% version %] [% timestamp %]
// ----------------------------------------------------------------------------
// NOTICE:
//      Copyright (C) Bloomberg L.P., [% year.format %]
//      All Rights Reserved.
//      Property of Bloomberg L.P. (BLP)
//      This software is made available solely pursuant to the
//      terms of a BLP license agreement which governs its use.
// ------------------------------- END-OF-FILE --------------------------------
