#!/bin/sh

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     platform=Linux;;
    Darwin*)    platform=Mac;;
    CYGWIN*)    platform=Cygwin;;
    MINGW*)     platform=MinGw;;
    MSYS_NT*)   platform=Git;;
    *)          platform="UNKNOWN:${unameOut}"
esac
echo ${machine}
realpath() (
    OURPWD=$PWD
    cd "$(dirname "$1")"
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")"
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD"
    echo "$REALPATH"
)

SCRIPT=$(realpath "$0")
MY_LIB_PATH="$(dirname $SCRIPT)/lib"

if [ "${platform}" == "Cygwin" ]; then
    SCRIPT=$(cygpath -aw ${SCRIPT})
fi

# Find suitable python version and invoke the tool.
for pyver in 3.10 3.9 3.8 3.7 3.6 3 ""; do
    python$pyver -V > /dev/null 2>&1 && exec env PYTHONPATH="$PYTHONPATH:${MY_LIB_PATH}/lib" python$pyver "${SCRIPT}.py" "$@"
done
echo "No appropriate python interpreter found." >&2
exit 1
