#!/usr/bin/env bash

# Script invoked by Jenkins to run bde_verify.

echo "INVOKED ARGS ARE <<$*>>"

NODE=$1
HOST=${NODE%%+++*}
UFID=$2
WORKSPACE=$3
BSL_FLAVOUR=${4-internal}
TARGET_UOR=${5-bsl bde bce bte bae bbe bsi}

JOBS=8
if [[ "$UFID" == "dbg_exc_mt" && "$NODE" == "nylnxbldo2+++gcc-4.3.2" ]]
then
    JOBS=16
fi

VD=$WORKSPACE/bde-verify
EXE=$VD/Linux-gcc-4.8.1/bde_verify
export VD EXE

BDE_VERIFY="$VD/scripts/build_verify"

function ts () { date +"%Y%m%d-%H%M%S"; }

echo "======================================================"
echo "Running on node '$NODE' (host $HOST)"
echo "'hostname'" is $(hostname)
echo "UFID is '$UFID' (JOBS is '$JOBS')"
echo "WORKSPACE is '$WORKSPACE'"
echo "BSL flavour is '$BSL_FLAVOUR'"
echo "Building target '$BUILD' (CMD_ARG is '$CMD_ARG')"
echo "Building UOR '$TARGET_UOR'"
echo "======================================================"

BDE_ROOT=$WORKSPACE/bde-core
BDE_PATH=\
$WORKSPACE/bde-tools:\
$WORKSPACE/bsl-${BSL_FLAVOUR}:\
$BDE_ROOT:\
$WORKSPACE/bde-bdx:\
$WORKSPACE/bde-bb

export BDE_PATH BDE_ROOT

# /opt/swt/bin for gmake
# /usr/ccs/bin for ar on Sun
PATH=/opt/swt/bin:/usr/ccs/bin:$PATH

HEADER_LOG=$WORKSPACE/log-header-deploy.`ts`

echo "++++++++++++++++++++++  $(ts):" \
     "Deploying headers for all uors (logged to $HEADER_LOG)"

$WORKSPACE/bde-tools/bin/bde_build.pl \
    -k -c bde_verify -DCC="$BDE_VERIFY" -DCXX="$BDE_VERIFY" \
    -O -Re -j${JOBS} -t $UFID -Minstall_include $TARGET_UOR > $HEADER_LOG 2>&1

RESULT=$?
if [ $RESULT -ne 0 ]
then
    echo "++++++++++++++++++++++  FAIL FAIL FAIL " \
         "Deploying headers for $TARGET_UOR - error $RESULT"
    echo See $HEADER_LOG

    echo "Tail end of $HEADER_LOG:"
    tail -10 $HEADER_LOG

    exit $RESULT
else
    rm $HEADER_LOG
fi

echo "++++++++++++++++++++++  $(ts) Building $TARGET_UOR"

$WORKSPACE/bde-tools/bin/bde_build.pl \
    -k -c bde_verify -DCC="$BDE_VERIFY" -DCXX="$BDE_VERIFY" \
    -O -Re -j${JOBS} -t $UFID $TARGET_UOR

exit 0

RESULT=$?
if [ $RESULT -ne 0 ]
then
    echo "++++++++++++++++++++++  FAIL FAIL FAIL " \
         "Building $TARGET_UOR - error $RESULT"
    exit $RESULT
fi

## ----------------------------------------------------------------------------
## Copyright (C) 2014 Bloomberg Finance L.P.
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to
## deal in the Software without restriction, including without limitation the
## rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
## IN THE SOFTWARE.
## ----------------------------- END-OF-FILE ----------------------------------
