tplttrait.cpp:10:63: warning: MA02: Allocator not passed to member e
struct A { E e; D<int> d; C c; B<int> b;  A(bslma::Allocator* alloc = 0) { } };
                                            ~~~~~~~~~~~~~~~~~~^~~~~~~~~
tplttrait.cpp:10:63: warning: MA02: Allocator not passed to member d
struct A { E e; D<int> d; C c; B<int> b;  A(bslma::Allocator* alloc = 0) { } };
                                            ~~~~~~~~~~~~~~~~~~^~~~~~~~~
2 warnings generated.
