csafmt_nonascii.t.cpp:1:6: warning: NA01: Non-ASCII characters
// abÞßëcd¶¥¶×ef
     ^~~
csafmt_nonascii.t.cpp:1:14: warning: NA01: Non-ASCII characters
// abÞßëcd¶¥¶×ef
          ^~~~
csafmt_nonascii.t.cpp:3:5: warning: NA01: Non-ASCII characters
    ¶¥×±
    ^~~~
csafmt_nonascii.t.cpp:4:5: warning: NA01: Non-ASCII characters
    ¶¥×±®
    ^~~~~
csafmt_nonascii.t.cpp:5:5: warning: NA01: Non-ASCII characters
    ¶¥×±®«
    ^~~~~~
5 warnings generated.
