# MAKEFILE FOR WrapComs.tsk generated by pcomp

TASK=WrapComs.tsk
IS_CPPMAIN=yes
IS_OPTIMIZED=yes
USER_CPPFLAGS += -I.

OBJS= \
WrapComs.o \
commentparagraph.o \
filereader.o \
filewriter.o \
lineutils.o

LIBS=

MKINCL?=/bbsrc/mkincludes/
include ${MKINCL}machdep.newlink
include ${MKINCL}linktask.newlink
